auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

title: jimzhao.com
url: http://jimzhao.com
feed: /atom.xml
author_info: <a href="http://jimzhao.com/">jimzhao</a>
